from calc import (
    calc_big_number_rate,
    calc_big_number_trend,
    calc_clean_card_percent,
    calc_clean_card_trend,
    calc_fir_percent,
    calc_fir_trend,
    calc_gir_percent,
    calc_gir_trend,
    calc_handicap_index,
    calc_handicap_trend,
    calc_one_putt_percent,
    calc_one_putt_trend,
    calc_par_or_better_percent,
    calc_pob_trend,
    calc_putts_gir_trend,
    calc_putts_per_gir,
    calc_putts_per_round,
    calc_putts_trend,
    calc_scoring_average,
    calc_scoring_trend,
    calc_scramble_percent,
    calc_scramble_trend,
    calc_three_putt_percent,
    calc_three_putt_trend,
)

STAT_CATALOG: list = [
    {
        "key": "handicap",
        "label": "Handicap",
        "suffix": "",
        "higher_better": False,
        "color": (64, 196, 255),
        "fn_primary":   lambda l20, b8, c, i9: calc_handicap_index(l20, i9),
        "fn_secondary": lambda l20, b8, c, i9: calc_handicap_index(l20[1:], i9),
        "trend_fn":     lambda all_r, c, i9: calc_handicap_trend(all_r, i9),
        "blank_text": "Play 3+ rounds to see handicap",
    },
    {
        "key": "score",
        "label": "Avg Score",
        "suffix": "",
        "higher_better": False,
        "color": (64, 255, 128),
        "fn_primary":   lambda l20, b8, c, i9: calc_scoring_average(b8),
        "fn_secondary": lambda l20, b8, c, i9: calc_scoring_average(l20),
        "trend_fn":     lambda all_r, c, i9: calc_scoring_trend(all_r),
        "blank_text": "Play a round to see scoring avg",
    },
    {
        "key": "fir",
        "label": "FIR",
        "suffix": "%",
        "higher_better": True,
        "color": (255, 220, 64),
        "fn_primary":   lambda l20, b8, c, i9: calc_fir_percent(b8, c),
        "fn_secondary": lambda l20, b8, c, i9: calc_fir_percent(l20, c),
        "trend_fn":     lambda all_r, c, i9: calc_fir_trend(all_r, c),
        "blank_text": "Play a round to see FIR %",
    },
    {
        "key": "gir",
        "label": "GIR",
        "suffix": "%",
        "higher_better": True,
        "color": (255, 128, 64),
        "fn_primary":   lambda l20, b8, c, i9: calc_gir_percent(b8),
        "fn_secondary": lambda l20, b8, c, i9: calc_gir_percent(l20),
        "trend_fn":     lambda all_r, c, i9: calc_gir_trend(all_r),
        "blank_text": "Play a round to see GIR %",
    },
    {
        "key": "putts",
        "label": "Putts / Rnd",
        "suffix": "",
        "higher_better": False,
        "color": (160, 128, 255),
        "fn_primary":   lambda l20, b8, c, i9: calc_putts_per_round(b8),
        "fn_secondary": lambda l20, b8, c, i9: calc_putts_per_round(l20),
        "trend_fn":     lambda all_r, c, i9: calc_putts_trend(all_r),
        "blank_text": "Play a round to see putts",
    },
    {
        "key": "scramble",
        "label": "Scramble",
        "suffix": "%",
        "higher_better": True,
        "color": (255, 64, 128),
        "fn_primary":   lambda l20, b8, c, i9: calc_scramble_percent(b8, c),
        "fn_secondary": lambda l20, b8, c, i9: calc_scramble_percent(l20, c),
        "trend_fn":     lambda all_r, c, i9: calc_scramble_trend(all_r, c),
        "blank_text": "Play a round to see scramble %",
    },
    {
        "key": "one_putt",
        "label": "1-Putt %",
        "suffix": "%",
        "higher_better": True,
        "color": (128, 200, 255),
        "fn_primary":   lambda l20, b8, c, i9: calc_one_putt_percent(b8),
        "fn_secondary": lambda l20, b8, c, i9: calc_one_putt_percent(l20),
        "trend_fn":     lambda all_r, c, i9: calc_one_putt_trend(all_r),
        "blank_text": "Play a round to see stats",
    },
    {
        "key": "three_putt",
        "label": "3-Putt %",
        "suffix": "%",
        "higher_better": False,
        "color": (255, 100, 100),
        "fn_primary":   lambda l20, b8, c, i9: calc_three_putt_percent(b8),
        "fn_secondary": lambda l20, b8, c, i9: calc_three_putt_percent(l20),
        "trend_fn":     lambda all_r, c, i9: calc_three_putt_trend(all_r),
        "blank_text": "Play a round to see stats",
    },
    {
        "key": "putts_gir",
        "label": "Putts/GIR",
        "suffix": "",
        "higher_better": False,
        "color": (200, 160, 255),
        "fn_primary":   lambda l20, b8, c, i9: calc_putts_per_gir(b8),
        "fn_secondary": lambda l20, b8, c, i9: calc_putts_per_gir(l20),
        "trend_fn":     lambda all_r, c, i9: calc_putts_gir_trend(all_r),
        "blank_text": "Play a round to see stats",
    },
    {
        "key": "pob",
        "label": "Par/Better %",
        "suffix": "%",
        "higher_better": True,
        "color": (100, 255, 180),
        "fn_primary":   lambda l20, b8, c, i9: calc_par_or_better_percent(b8, c),
        "fn_secondary": lambda l20, b8, c, i9: calc_par_or_better_percent(l20, c),
        "trend_fn":     lambda all_r, c, i9: calc_pob_trend(all_r, c),
        "blank_text": "Play a round to see stats",
    },
    {
        "key": "clean_card",
        "label": "Clean Card %",
        "suffix": "%",
        "higher_better": True,
        "color": (255, 220, 120),
        "fn_primary":   lambda l20, b8, c, i9: calc_clean_card_percent(b8, c),
        "fn_secondary": lambda l20, b8, c, i9: calc_clean_card_percent(l20, c),
        "trend_fn":     lambda all_r, c, i9: calc_clean_card_trend(all_r, c),
        "blank_text": "Play a round to see stats",
    },
    {
        "key": "big_number",
        "label": "Blow-up %",
        "suffix": "%",
        "higher_better": False,
        "color": (255, 80, 80),
        "fn_primary":   lambda l20, b8, c, i9: calc_big_number_rate(b8, c),
        "fn_secondary": lambda l20, b8, c, i9: calc_big_number_rate(l20, c),
        "trend_fn":     lambda all_r, c, i9: calc_big_number_trend(all_r, c),
        "blank_text": "Play a round to see stats",
    },
]

DEFAULT_DASHBOARD_STATS: list = ["handicap", "score", "fir", "gir", "putts", "scramble"]
